### ISSUE TITLE
touchscreen goes black on execution of package

### ISSUE THREAD

**Issue by RogueM** [RPi-Distro/raspberrypi-sys-mods#11]
For the last few drops I have noticed that each time `raspberrypi-sys-mods` gets an upgrade as part of a system `apt-get upgrade`, the RPF touchscreen goes black. I have also experienced that over HDMI feeding up a lapdock (standard HDMI displays are unaffected).

Today I went back to an earlier Raspbian image just to test the theory that `raspberrypi-sys-mod` was the culprit, and confirmed it is. In fact I can produce the problem on demand like so:

> sudo apt-get remove raspberrypi-sys-mod
> sudo apt-get install raspberrypi-sys-mod

**Comment by spl237** [comment]
Do you mean it goes black temporarily during the update and recovers at the end, or that it goes black and stays back until you restart, or goes black and never recovers?

**Comment by RogueM** [comment]
no, it never recovers. I need to reboot it over ssh (which is potentially dangerous if there is a kernel swap going on but hey!).

I'm also investigating this issue, which I have a hunch is related:
https://www.raspberrypi.org/forums/viewtopic.php?f=108&t=120968&p=1083463&hilit=sleep#p1083463

... my current theory is that when the system goes into sleep the service kicks in and shuts down the backlight. This is pure speculation however, but I'm going to try to kill that service/facility for a while and see if I still have problem waking up the touchscreen from sleep...

**Comment by spl237** [comment]
OK, so when you say it never recovers, you mean it only recovers when you reboot it?

**Comment by RogueM** [comment]
yes, correct. I can do any amount of work over ssh when the problem occurs (whether those 2 problems are related, which I have not gathered evidence yet that they are).

**Comment by spl237** [comment]
OK, we'll investigate. Probably won't be until after Christmas now though! Thanks for the report.

**Comment by RogueM** [comment]
np... I'll post here if I find any additional info worth relating.

**Comment by RogueM** [comment]
right, looks like I can trigger the issue by doing:

`sudo systemctl restart rpi-display-backlight`

... which I suspect occurs as part of the package postinst?

**Comment by spl237** [comment]
Not directly, but something else may be triggering it. The right answer is probably that restarting that service should work properly - I'll flag it to the relevant people.
