### ISSUE TITLE
sourcing of gettext.sh causes error message at login

### ISSUE THREAD

**Issue by mapausch** [RPi-Distro/raspberrypi-sys-mods#23]
with installed raspberrypi-sys-mods the error message "-bash: gettext.sh: Datei oder Verzeichnis nicht gefunden" comes up after successful login.

("Datei oder Verzeichnis nicht gefunden" translated to english: File or directory not found )

tracked the message down to /etc/profile.d/wifi-country.sh where in line 4
the file gettext.sh is sourced:

```
(
        export TEXTDOMAIN=wifi-country

        . gettext.sh
```

**Comment by spl237** [comment]
gettext.sh is required for multi-language support. I can repeat the error message you show by deleting the file /usr/bin/gettext.sh, so it has presumably either been deleted or not been installed on your system.

"sudo apt-get install --reinstall gettext" should fix it.

**Comment by spl237** [comment]
Hang on - that seems not to reinstall the .sh file - I'll try to find what installs that.

**Comment by spl237** [comment]
"sudo apt-get install --reinstall gettext-base" should fix it.
