### ISSUE TITLE
.DS_Store files in raspberrypi-sys-mod package

### ISSUE THREAD

**Issue by peterryan** [RPi-Distro/raspberrypi-sys-mods#3]
Hi,
Super-minor issue to report; there's some .DS_Store files leaked into the raspberrypi-sys-mod package in the following locations:

/usr/.DS_Store
/usr/lib/.DS_Store
/lib/.DS_Store
/lib/udev/.DS_Store

I can't actually see those files in the git repo so presumably an issue in packaging?

Anyway... totally a non-issue, which I wouldn't bother to mention except... OCD!! :-D

Peter.

**Comment by XECDesign** [comment]
Will be gone with the next build.

**Comment by peterryan** [comment]
Wow that was quick - cheers!
