### ISSUE TITLE
wifi-country should be quiet if wifi is disabled by user choice

### ISSUE THREAD

**Issue by ali1234** [RPi-Distro/raspberrypi-sys-mods#31]
If the user disables wifi in config.txt before setting the country they will still see the message "Wi-fi is disabled because the country is not set." on logging in. However, they will be unable to set the country using raspi-config, because it will detect that the wifi is disabled by the user and refuse to set the country.

**Comment by XECDesign** [comment]
Should be fixed by https://github.com/RPi-Distro/raspberrypi-net-mods/commit/f68bd032cc8bb530232d025b2aa035399a9ba5be#diff-898421283b2feb5441f85e328570af42
