### ISSUE TITLE
Buster gpio udev rules

### ISSUE THREAD

**Issue by bcroston** [RPi-Distro/raspberrypi-sys-mods#32]
In the Debian-maintained Buster package for RPi.GPIO, the package maintainer has included the udev rules in the 'rpi.gpio' debian package.  It uses the 'dialout' group rather than the 'gpio' group.  Could there be a conflict with 'raspberrypi-sys-mods/etc.armhf/udev/rules.d/99-com.rules'?  It suspect it will cause a lot of confusion with end users following existing guides found around the web.  A good example would be when the user has added the 'www-data' user to the 'gpio' group so that website scripts can use gpio.

**Comment by XECDesign** [comment]
It's worth testing, but the sys-mods version should run last and take priority over the version shipped in rpi.gpio. So, the old behaviour should be preserved within our Raspbian images.

**Comment by XECDesign** [comment]
Okay to close?

**Comment by bcroston** [comment]
It seems to work fine now we have done a release

**Comment by XECDesign** [comment]
Thanks, Ben.
