### ISSUE TITLE
Re-enable rtl8192cu ?

### ISSUE THREAD

**Issue by macmpi** [RPi-Distro/raspberrypi-sys-mods#37]
Following [4.19.40 and newer and improved driver](https://github.com/raspberrypi/linux/issues/2979), maybe one can remove [related blacklist](https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/master/etc.armhf/modprobe.d/blacklist-rtl8192cu.conf)?

**Comment by XECDesign** [comment]
@popcornmix

**Comment by XECDesign** [comment]
Swap would probably be safest until 8192cu is removed from the downstream kernel?
