### ISSUE TITLE
No README and repository description

### ISSUE THREAD

**Issue by AlekSi** [RPi-Distro/raspberrypi-sys-mods#4]
It's hard to understand what it is without a README.

**Comment by XECDesign** [comment]
It's hard to describe what this package is for other than to say it's for raspberry pi system mods... which is already in the title. Suggestions?

**Comment by AlekSi** [comment]
Well, to describe what is system mods?
Short README is better than nothing. If it's something I'm not looking for, I can read README and move to next repository. Otherwise, I have to figure it out from sources.

**Comment by pelwell** [comment]
"A collection of Raspberry Pi-sourced system configuration files and associated scripts"?

**Comment by XECDesign** [comment]
Added that as the description. Thanks.

**Comment by AlekSi** [comment]
It probably would be useful to describe (or add a link to description) its place in the whole build process.
Btw, first Google hit for "raspberry pi system mods": http://www.techrepublic.com/pictures/raspberry-pi-10-fun-and-fantastic-mods/. 😄
