### ISSUE TITLE
Where is the 20210125 update ?? 

### ISSUE THREAD

**Issue by FredericGuilbault** [RPi-Distro/raspberrypi-sys-mods#41]
Hi, 
My dev box received an update of raspberrypi-sys-mods numbered 20210125 from raspberrypi.org

 signed by  ` — Serge Schneider Mon, 25 Jan 2021 16:03:24 +0000 `

But I don't find it anywhere in :

https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/master/debian/changelog

Im confused, is this voluntary ?

**Comment by FredericGuilbault** [comment]
The .dsc control file stipulate that source repository of the package is your  github repository. 

```
Vcs-Browser: https://github.com/RPi-Distro/raspberrypi-sys-mods
Vcs-Git: git://git@github.com:RPi-Distro/raspberrypi-sys-mods.git
```

http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-sys-mods/raspberrypi-sys-mods_20210125.dsc

**Comment by XECDesign** [comment]
I don't generally push things to git immediately, but it should be there now.

**Comment by FredericGuilbault** [comment]
@XECDesign  Any plans to add repositories in pi-get instead of post-inst scripts, This is for the least.  ...not the most iconic way to add a repository to a distribution.

**Comment by OmgImAlexis** [comment]
> I don't generally push things to git immediately, but it should be there now.

You should really look into changing this practise. The source should be pushed and viewable before updates go out.

**Comment by robertoschwald** [comment]
... and do not enable the repo by default. 
This smells.
