### ISSUE TITLE
VScodium: Privacy instead of capitalism.

### ISSUE THREAD

**Issue by ricardoandren** [RPi-Distro/raspberrypi-sys-mods#44]
Why not replace microsofts repository by the vscodium repo since this is probably done for cash, since its pushed onto people without an obvious warning. There were obvious other free options but they chose not too? Why?

https://vscodium.com/

**Comment by pelwell** [comment]
Closing pointless duplicate issue.

**Comment by ricardoandren** [comment]
Pointless? I gave an alternative but alright, I know you want to keep sending ips to microsoft, which they can use to figure out who has a raspberry pi and then keep advertising about anything related to a raspberry pi.
