### ISSUE TITLE
Move the management of  /etc/apt/sources.list.d/vscode.list in a separate package.

### ISSUE THREAD

**Issue by FredericGuilbault** [RPi-Distro/raspberrypi-sys-mods#50]
Still I don't know where you are about this problem, ill keep suggest new possibility. 

This one would be to separate the management of the file  /etc/apt/sources.list.d/vscode.list and the related key management in a separate package that do one thing (adding M$ repo) and do it well.

**Comment by jpmcneely** [comment]
This is the correct solution.  Make it a package.  There is no need to make this part of the existing sys-mods.

**Comment by XECDesign** [comment]
That's not one of the options we're considering.

**Comment by FredericGuilbault** [comment]
Thx, at least that make it clear. So we know now.  Silence is often the worst than unpopular answers.

**Comment by RubenNL** [comment]
> That's not one of the options we're considering.

Why not? What makes a postinstall script superior to a package?
