### ISSUE TITLE
Raspberry Pi OS Image is missing Microsoft Repository

### ISSUE THREAD

**Issue by chrisdecker1201** [RPi-Distro/raspberrypi-sys-mods#54]
Hello,

I found out that when you generate an own Raspberry Pi Image with *pi-gen* you will not have and get any Microsoft Repository. Because at the moment you only add the Microsoft repository if the *raspberrypi-sys-mods* version is lower than or unequal to the current version.

Greets
Christian

**Comment by XECDesign** [comment]
Thanks Christian. There's the possibility that the repo will no longer be necessary pulled from sys-mods, so there's no point adding it to pi-gen until I know whether it's here to stay or not.
