### ISSUE TITLE
sshpasswd.sh fails if user is not allowed to run passwordless sudo

### ISSUE THREAD

**Issue by paulchen** [RPi-Distro/raspberrypi-sys-mods#7]
/etc/profile.d/sshpasswd.sh assumes that any user logging in via SSH is allowed to run the command

`sudo -n grep -E '^pi:' /etc/shadow`

That assumption is just plain wrong.

**Comment by spl237** [comment]
Yes, we know - and if you've got any better ideas as to how to check if the pi user is still using the default password without the need for sudo, we'd be very interested to hear them, given the password file is only readable by root...
