### ISSUE TITLE
"imager_custom set_wlan" generates script but does not escape special characters properly

### ISSUE THREAD

**Issue by maxnet** [RPi-Distro/raspberrypi-sys-mods#72]
Original issue: https://github.com/raspberrypi/rpi-imager/issues/581

If the user enters a SSID in Imager's advanced settings that contains a $ and writes RPI OS, /etc/wpa_supplicant/wpa_supplicant.conf does not get written correctly.

Imager correctly writes a firstrun.sh that calls: /usr/lib/raspberrypi-sys-mods/imager_custom set_wlan '$1234' 'somehash' 'GB'
And that should work because the shell does not see it as a variable if the $ is inside single quotes.

But your script in turns seems to write out a set-wlan helper script that contains: if raspi-config nonint do_wifi_ssid_passphrase "$1234"
And with double quotes $1 does is seen as variable.

Probably also gives problems if the SSID contains a " but haven't tried.

**Comment by MichaIng** [comment]
PR up to fix this: #73
