### ISSUE TITLE
sshpasswd.sh causes security information warnings

### ISSUE THREAD

**Issue by marcust** [RPi-Distro/raspberrypi-sys-mods#8]
The new sshpasswd.sh expects the executing user to have sudo without password rights, if that is not the case at least in my setup (which is pretty much default, besides the user configuration) it will send an email warning about security issues. 

On one of my machines that is triggered by connecting via ssh, on one other it is actually triggered by an init script of one of the processes. In the first case it just fails with "a password is required", in the second case it warn that "user X is not in sudoers". 

In itself that is a quite useful feature, but I might not be the only one who gets confused if systems send you emails warning about someone grepping in your /etc/shadow file.

**Comment by spl237** [comment]
This is a known problem - root access is required to read the password shadow file. On standard images, passwordless sudo is enabled for the pi user, so this works - if people have changed their setup, then security warnings will be generated.

We are working on ways around this at the moment; probably involving a systemd process running with root access which carries out the check - when we've got something we're happy with, we'll push an update.
