### ISSUE TITLE
imager_set_custom using uuid which is not always available

### ISSUE THREAD

**Issue by maxnet** [RPi-Distro/raspberrypi-sys-mods#86]
Since https://github.com/RPi-Distro/raspberrypi-sys-mods/commit/c8a2ee7031047f54568dd2828b3dabfcce386fd5 you are using "uuid" in imager_set_custom

There are end-user reports suggesting that is MIA in RPI OS Lite: https://forums.raspberrypi.com/viewtopic.php?p=2165884#p2165884

**Comment by XECDesign** [comment]
Thanks!
