### ISSUE TITLE
Initrd rootfs resize fails on RPi5

### ISSUE THREAD

**Issue by syrykh** [RPi-Distro/raspberrypi-sys-mods#87]
Hi,

While trying `2023-12-11-raspios-bookworm-arm64-lite.img` on a RPi5 I observed that sometimes (not 100%) `resize2fs` fails on 1st boot:

![resize2fs-issue](https://github.com/RPi-Distro/raspberrypi-sys-mods/assets/7023634/66a6b3f0-191a-4798-af82-09324970f956)

You can find some more details below.

I had a suspicion that `/dev/mmcblk0p2` is not yet available when `resize2fs` is invoked. And just because RPi5 is faster than RPi4 (which never had this issue), the issue became visible. To confirm this suspicion I added some logs and `sleep` to `initramfs-tools/scripts/local-premount/firstboot`:
```patch
@@ -36,6 +36,13 @@ do_resize () {
     return 1
   fi
 
+  echo Before sleep
+  ls -la /dev | grep mmc
+
+  sleep 1
+  echo After sleep
+  ls -la /dev | grep mmc
+
   resize2fs -f -p "$DEV"
   RET="$?"
   if [ "$RET" -ne 0 ]; then
```

And that's what I got, which confirmed absence of `/dev/mmcblk0p2` before sleep:

![resize2fs-with-logs](https://github.com/RPi-Distro/raspberrypi-sys-mods/assets/7023634/0fd7705b-30d7-445e-83a5-793c7f97c154)

So, there's a need to wait for root partition device to become available, before invoking `resize2fs`.

My suggestion is straight-forward: retry test `[ -b "$DEV" ]` with delay.
```patch
@@ -30,12 +30,33 @@ get_variables () {
   fi
 }
 
+retry () {
+  local retries=$1
+  local delay=$2
+  shift 2
+
+  for i in $(seq 1 "$retries"); do
+    "$@" \
+      && return 0
+
+    sleep "$delay"
+  done
+
+  return 1
+}
+
 do_resize () {
   if ! parted -m "$ROOT_DEV" u s resizepart "$ROOT_PART_NUM" "$TARGET_END"; then
     FAIL_REASON="Partition table resize of the root partition ($DEV) failed\n$FAIL_REASON"
     return 1
   fi
 
+  # Wait up to 3s for root partition to become available
+  if ! retry 30 0.1s [ -b "$DEV" ]; then
+    FAIL_REASON="Root partition ($DEV) is not available\n$FAIL_REASON"
+    return 1
+  fi
+
   resize2fs -f -p "$DEV"
   RET="$?"
   if [ "$RET" -ne 0 ]; then
```

But maybe there's a better/proper way of waiting for the `/dev/mmcblk0p2` device?

Your assistance in resolving this would be greatly appreciated. Thanks!

**Comment by XECDesign** [comment]
Hmm, that's strange.

I previously added `local_device_setup` [here](https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/95e7f165cde2d999b9c510640fe69c534701a185/initramfs-tools/scripts/local-premount/firstboot#L17), which [should wait for the device to show up](https://salsa.debian.org/kernel-team/initramfs-tools/-/blob/v0.142/scripts/local?ref_type=tags#L72). I haven't seen the problem since then.

Would you be able to trace what happens within that function?

**Comment by syrykh** [comment]
That's what I get when changing top `set -e` to `set -ex`:

![firstboot-set-x](https://github.com/RPi-Distro/raspberrypi-sys-mods/assets/7023634/293aeb60-3b60-4dff-b8db-be66d1f9bbbc)

It seems that `local_device_setup` passed successfully. Weird.

**Comment by XECDesign** [comment]
I'm... having trouble figuring out how that possibly makes sense. Anything interesting in `dmesg` that maybe shows the device disappearing?

**Comment by XECDesign** [comment]
Or, maybe parted calls partprobe (or something equivalent) after editing the partition table, so /dev/mmcblk0p2 disappears for a split second.

**Comment by syrykh** [comment]
It should be related with `parted`. I have added `ls -la /dev | grep mmc` before and after the `parted` invocation.

![00414](https://github.com/RPi-Distro/raspberrypi-sys-mods/assets/7023634/3051b623-1031-462f-ba41-b8f3ecc95b40)

This time `resize2fs` passed, but that just because my logs impacted timings. But we can see that while `mmcblk0p2` was there before `parted` invocation, it was gone right after it.

**Comment by XECDesign** [comment]
Okay, yeah that makes sense then. Not sure what the best solution is. Maybe a `wait_for_udev 10` right before the `resize2fs`.

**Comment by MichaIng** [comment]
We do this in our partition+fs resize script:
```
partprobe "$ROOT_DRIVE"
partx -u "$ROOT_DRIVE"
sleep 0.5
```
We resize the partition via `sfdisk`. Not sure whether `parted` implies telling the kernel to recheck partitions (what `partprobe` does)? Since we had rare cases (probably not RPi and long time ago), where `partprobe` alone somehow did not work, we added `partx -u` as redundant failsafe step. And since we also found partitions to be missing for some fraction of a second after this, we added this 0.5s sleep.

Not sure whether udev is immediately and remains busy until the partition devices appear, but `wait_for_udev` sounds reasonable in the initramfs in this case.

**Comment by XECDesign** [comment]
Thanks for confirming the theory as well. If you're doing this outside of initramfs, I wonder if something like `udevadm settle -t 10 -E "$ROOT_PART"` would solve it for you as well (assuming `wait_for_udev` works), without having to resort to a `sleep`.

**Comment by syrykh** [comment]
I tried 12 times with `wait_for_udev 10` before `resize2fs`, it worked fine.

**Comment by XECDesign** [comment]
Many thanks for troubleshooting and testing this!

**Comment by MichaIng** [comment]
Great. Yes indeed then `udevadm settle` should work for us as well, being less arbitrary. I wasn't aware of the `-E` option, that is great when waiting for particular device nodes 👍.

**Comment by syrykh** [comment]
Thanks a lot for addressing this issue!
