### ISSUE TITLE
sshpasswd.sh triggers security notifications if user doesn't have sudo permissions

### ISSUE THREAD

**Issue by m3phisto** [RPi-Distro/raspberrypi-sys-mods#9]
Problem:
The sshpasswd.sh script in etc/profile.d performs the check even if the current user is not able to perform the sudo action required. This triggers a security notice (and in my case an email).

Mitigation:
A possible solution would be to check the "$USERNAME" variable for equality with "pi"/"root" before calling "check_hash".
I can prepare a Pull Request if necessary.

**Comment by XECDesign** [comment]
See #8

**Comment by spl237** [comment]
Checking $USERNAME won't help if the pi user has disabled passwordless sudo. We're working on a proper solution for this - bear with us.

**Comment by m3phisto** [comment]
Sorry for reporting a known issue. I didn't check closed issues (as this problem clearly persists).
