### ISSUE TITLE
Cloud-init support

### ISSUE THREAD

**Issue by matuzalemmuller** [RPi-Distro/raspberrypi-sys-mods#91]
Hello,

I've read in a few issues that cloud-init support is coming. I'm curious if there's a timeline for adding the feature - I've been considering modifying the firstboot script to perform the initial setup I need, but if cloud-init is on the horizon, I can wait until then.

Thank you!

**Comment by XECDesign** [comment]
I think modifying the firstboot script is the way to go. Unfortunately cloud-init doesn't seem to be on the horizon yet and there's no timeline.

**Comment by matuzalemmuller** [comment]
Thanks for the reply, I will close this for now.
